global without sharing class ProgramConstants {
    global static final String COSPONSORGROUP = 'CoSponsorGroup';
    global static final String COSPONSORADMIN = 'CoSponsorAdmin';
    global static final String PARTNERIDFIELD = 'PartnerId__c';
    global static final String RECORDTYPEIDFIELD = 'RecordTypeId';
    global static final String REPEATPROGRAMFIELD = 'RepeatProgramId__c';
    global static final String SUBSTAGEFIELD = 'SubStage__c';
    global static final String DRAFTVERSION = 'Draft';
    global static final String FINALVERSION = 'Final';
}
