public without sharing class TestDataFactoryConstants {
    public final static String ACCOUNTOBJECT = 'Account';
    public final static String ACCOUNTCONTACTRELATIONOBJECT = 'AccountContactRelation';
    public final static String CONTACTOBJECT = 'Contact';
    public final static String CONTACTSTAGINGTABLEOBJECT = 'ContactStagingTable__c';
    public final static String CHECKLISTOBJECT = 'Checklist__c';
    public final static String CITATIONOBJECT = 'Citation__c';
    public final static String LOOPDDPOBJECT = 'Loop__DDP__c';
    public final static String NARRATIVETYPEOBJECT = 'NarrativeType__c';
    public final static String PROGRAMDOCUMENTGENERATIONOBJECT = 'ProgramDocumentGeneration__c';
    public final static String PROGRAMDOCUMENTGENERATIONSUBSTAGEOBJECT = 'ProgramDocumentGenerationSubStage__c';
    public final static String PROGRAMOBJECT = 'Program__c';
    public final static String PROGRAMCHECKLISTOBJECT = 'ProgramChecklist__c';
    public final static String PROGRAMSESSIONOBJECT = 'ProgramSession__c';
    public final static String PROGRAMSESSIONREADINGOBJECT = 'ProgramSessionReading__c';
    public final static String USEROBJECT = 'User';

    public final static String BUDGETAMOUNTFIELD = 'BudgetAmount__c';
    public final static String EMAILFIELD = 'Correspondence_Email__c';
    public final static String FIRSTNAMEFIELD = 'First_Name__c';
    public final static String LASTNAMEFIELD = 'Last_Name__c';
    public final static String SUBSTAGEFIELD = 'SubStage__c';


    public final static String PROFILELFADMIN = 'LF Admin';
}
